# Generated by Django 5.0.4 on 2024-06-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extras',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='extras',
        ),
    ]
