services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: soap
      MYSQL_USER: adel
      MYSQL_PASSWORD: 071099
      MYSQL_ROOT_PASSWORD: 071099
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./Backend/src:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: soap
      DB_USER: adel
      DB_PASSWORD: 071099
      DB_HOST: db
      DB_PORT: 3306

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend/src:/app/src
    command: ["npm", "run", "dev"]
    depends_on:
      - web

volumes:
  mysql-data:
